sudo: required

services:
  - docker

language:
  - cpp

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudev-dev valgrind
  # install open-zwave
  - git clone https://github.com/OpenZWave/open-zwave.git
  - cd open-zwave
  - sudo make install
  - cd ..
  # install mosquitto
  - git clone https://github.com/eclipse/mosquitto.git
  - cd mosquitto
  - git checkout v1.5.8
  - make WITH_SRV=no WITH_UUID=no WITH_DOCS=no
  - sudo make WITH_DOCS=no install
  - cd ..
  # install gtest
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake .
  - sudo make install
  - cd ..

jobs:
  include:
    - &test
      stage: Tests
      compiler: gcc
      script:
        - cmake .
        - make all test
    - <<: *test
      compiler: clang

    - &stage
      stage: Dockers
      env:
        - BASE=ubuntu
        - TAG=latest
      install: skip
      script: &dock
        - cd docker
        - ./build_docker
